# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KDJ-wiki
email: esctrax@gmail.com
description: >-
  ※現在テスト中です<br>
  <br>
  KDJ-ONE の情報を有志で集めることを目的としたwikiです。<br>
  どなたでも編集していただけますが、Githubのグループに登録する必要がございます。
## localで動かすときは以下コメントアウト
baseurl: "/main" # the subpath of your site, e.g. /blog
url: "https://kdj-wiki.github.io" # the base hostname & protocol for your site, e.g. http://example.com
## localで動かすときは以下コメントアウト(ここまで)
twitter_username: esctrax
#github_username:  jekyll

# for git-wiki settings
show_downloads: false
git_branch: master
logo_url: https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/1122px-Wikipedia-logo-v2.svg.png
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# prose.io settings
prose:
  ignore: ['_layouts', '_config.yml']


